language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libudev-dev libxml2-dev

before_script:
  - git submodule update --init --recursive
  - cmake -Hexternal/sercomm -Bexternal/sercomm/_build -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build external/sercomm/_build --target install

script:
  - cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DWITH_PROT_MCB=ON
  - cmake --build _build

notifications:
  email: false
