language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libudev-dev

before_script:
  - git clone https://github.com/ingeniamc/sercomm.git _deps/sercomm
  - cmake -H_deps/sercomm -B_deps/sercomm/_build -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build _deps/sercomm/_build --target install

script:
  - cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build _build

notifications:
  email: false
